name: 'playwright-github-pages'
description: 'Playwright HTML Test Results with history'
author: 'Pavan Mudigonda'
branding:
  icon: 'layout'
  color: 'green'
inputs:
  playwright_results:
    description: 'Playwright test result data dir'
    required: true
    default: 'test-results'
  playwright_report:
    description: 'Allure report target dir'
    required: true
    default: 'test-results'
  gh_pages:
    description: 'Folder with gh-pages branch'
    required: true
    default: 'gh-pages'
  allure_history:
    description: 'Folder for allure history'
    required: true
    default: 'allure-history'
  subfolder:
    description: 'subfolder'
    required: false
    default: ''
  keep_reports:
    description: 'Keep X last reports'
    required: false
    default: '20'
  github_run_num:
    description: 'GitHub Actions build number'
    required: true
    default: ${{ github.run_number }}
  github_run_id:
    description: 'GitHub Actions run id'
    required: true
    default: ${{ github.run_id }}
  github_repo:
    description: 'GitHub repository'
    required: true
    default: ${{ github.repository }}
  github_repo_owner:
    description: 'GitHub repository owner'
    required: true
    default: ${{ github.repository_owner }}
  report_url:
    description: 'Use a custom URL instead of *.github.io'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'